### ISSUE TITLE
Dimension mismatch

### ISSUE THREAD

**Issue by leesin5079** [viv92/Frozen#1]
When i load checkpoint of pretrained ViT in vit.py, the size of the net is 512. But the d_ model parameter in Frozen_vit.py is 768, the error comes:
RuntimeError: Error(s) in loading state_dict for ViT:
size mismatch for img_emb.pos_emb: copying a param with shape torch.Size([257,512]) form checkpoint, the shape in current model is torch.Size([257, 768])
....
same error for every layer, how can i fix it?

**Comment by viv92** [comment]
vit.py and Frozen_vit.py generate two different models as they have different main() functions.

vit.py consists of the class defining the VIT architecture, with a sample main() function that depicts training VIT on CIFAR. In this sample main function, the d_model for VIT is set as 512. 

Frozen_vit.py implements the Frozen architecture, while importing the VIT class definition from vit.py. The main() function in Frozen_vit.py sets the d_model for VIT as 768. 

So the model checkpoints generated by vit.py and Frozen_vit.py can be loaded only in the respective scripts.

**Comment by leesin5079** [comment]
Got it, thanks for your reply. Can you please share the checkpoint of the vit in  Frozen_vit.py?

**Comment by viv92** [comment]
The checkpoint file is too big to be uploaded on github repo. So I'm sharing here as a google drive link:
https://drive.google.com/file/d/1-9972pqhBvVWZC1nA7nNCri9OtAjfis5/view?usp=share_link

This model checkpoint was generated after training for around 10k iterations.
You can generate your own checkpoints as well by running the Frozen_vit.py script

**Comment by leesin5079** [comment]
Thanks bro! The universe is cold, but you have a warm heart.
By the way, I trained the Frozen_vit for 20 epochs, but the model failed to converge. The loss kept above 20 and the batch_accuracy stayed below 40. 
Did you get the same result, and how can i improve it?

**Comment by accuracy-maker** [comment]
great work! I have a question.
```
def load_data():
    imgs_folder = 'dataset_coco_val2017/images/'
    captions_file_path = 'dataset_coco_val2017/annotations/captions_val2017.json'
    captions_file = open(captions_file_path)
    captions = json.load(captions_file)
    img_dict, img_cap_dict = {}, {}
    for img in captions['images']:
        id, file_name = img['id'], img['file_name']
        img_dict[id] = file_name
    for cap in captions['annotations']:
        id, caption = cap['image_id'], cap['caption']
        # use img_name as key for img_cap_dict
        img = img_dict[id]
        img_cap_dict[img] = caption
    return img_cap_dict
```
where should I download the img files?

**Comment by viv92** [comment]
You can download the coco val 2017 dataset from: https://cocodataset.org/#download

**Comment by accuracy-maker** [comment]
thanks bro!
